import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Sofia_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Suspense } from "react";
import GlobalLoader from "@/components/GlobalLoader";
// import Footer from "@/components/Footer";
// import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const sofia_Sans = Sofia_Sans({
  variable: "--font-sofia-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Boost your savings with ZenMicro’s cloud resource optimization",
  description: "Generated by create next app",
  icons: "/logo.png",
  openGraph: {
    title: "ZenMicro",
    description:
      "Boost your savings with ZenMicro’s cloud resource optimization",
    url: "https://sairahman312.vercel.app",
    siteName: "ZenMicro Logo",
    images: [
      {
        url: "https://sairahman312.vercel.app/logo.png",
        width: 1200,
        height: 630,
        alt: "ZenMicro Logo",
      },
      {
        url: "https://sairahman312.vercel.app/logoSquare.png",
        width: 1200,
        height: 1200,
        alt: "ZenMicro Logo",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "ZenMicro",
    description:
      "Get your book ghostwritten by professional writers with skill and passion.",
    images: [
      {
        url: "https://sairahman312.vercel.app/logo.png",
        width: 1200,
        height: 630,
        alt: "ZenMicro Logo",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable}  ${sofia_Sans.variable} antialiased bg-[#0F1433]`}
      >
        <main className=" ">
          <Header />
          <div className="pt-[100px] font-poppins">
            <Suspense fallback={<GlobalLoader />}>{children}</Suspense>
          </div>
        </main>
      </body>
    </html>
  );
}
